[font]

# normal.family = "Cascadia Code PL"
# bold.family = "Cascadia Code PL"
# italic.family = "Cascadia Code PL"
# bold_italic.family = "Cascadia Code PL"

size = 16.0

[window]

# for MacOS.
# not sure if it works on linux.
option_as_alt = "Both"
