#!/usr/bin/env bash

function error_handler() {
  echo >&2 "Exited with BAD EXIT CODE '${3}' in file '${1}' at line ${2}."
  exit "$3"
}
trap 'error_handler "${BASH_SOURCE[0]}" "${LINENO}" "$?"' ERR
set -o errtrace -o errexit -o nounset -o pipefail

script_dir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
export PATH="${script_dir}/../bin:$PATH"
export NO_TERM_LIMITS_TESTS_DIR="$script_dir"

if [[ -x "$HOME/.local/bin/mise" ]]; then
  eval "$("$HOME/.local/bin/mise" env -s bash)"
fi

test_files=$(find "${script_dir}/unit" -name "*.sh")
if [[ -n "$test_files" ]]; then
  while read -r test_file; do
    echo "Running $test_file"
    "$test_file"
  done <<<"$test_files"
fi
