#!/usr/bin/env python

import atexit
import os
import readline

history_path = os.path.expanduser("~/.pyhistory")


def save_history(history_path=history_path): import readline; readline.write_history_file(history_path);


history_lines = []
with open(history_path) as f: history_lines = f.readlines(); history_lines = list(dict.fromkeys(history_lines[-1000:]));

with open(history_path, 'w') as f: f.write("\n".join(history_lines));

if os.path.exists(history_path): readline.read_history_file(history_path)

atexit.register(save_history, history_path=history_path)
