#!/usr/bin/env bash

# we started with: https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
# this file is basically the above, but with some search and replaces that we performed on it.

function error_handler() {
  >&2 echo "Exited with BAD EXIT CODE '${2}' in ${0} script at line: ${1}."
  exit "$2"
}

trap 'error_handler ${LINENO} $?' ERR

set -o errexit
set -o errtrace
set -o pipefail
set -x

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if [ ! -f "$HOME/.zshrc" ]; then
  touch "$HOME/.zshrc"
fi

if [[ -z "$NO_TERM_LIMITS_PREFERRED_SHELL" ]]; then
  export NO_TERM_LIMITS_PREFERRED_SHELL=zsh
elif ! grep -qE '^(zsh|bash)$' <<<"$NO_TERM_LIMITS_PREFERRED_SHELL" ; then
  >&2 echo "ERROR: no-term-limits only supports zsh and bash but you have specified $NO_TERM_LIMITS_PREFERRED_SHELL. Please either unset this variable which will default to zsh or set it to bash"
  exit 1
fi

asdf_branch_name='v0.9.0'
vim_version='8.2.3768'
HOMEBREW_PREFIX="/usr/local"

function ubuntu_greater_than_18_04() {
  ubuntu_version="$(lsb_release -sr | sed 's/\.//')"
  [[ "$ubuntu_version" -gt "1804" ]]
}

function update_shell() {
  if [[ "$SHELL" != *"$NO_TERM_LIMITS_PREFERRED_SHELL" ]]; then
    local shell_path;
    shell_path="$(command -v "$NO_TERM_LIMITS_PREFERRED_SHELL")"
    local username_of_current_user
    username_of_current_user="$(whoami)"

    echo "Changing your shell to $NO_TERM_LIMITS_PREFERRED_SHELL ..."
    if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
      echo "Adding '$shell_path' to /etc/shells"
      sudo sh -c "echo $shell_path >> /etc/shells"
    fi

    local should_change_shell="false"
    if is_mac; then
      if dscl . -read "/Users/${username_of_current_user}" UniqueID > /dev/null; then
        should_change_shell="true"
      fi
    else
      # if you sign in via some sort of single sign on and do not have local accounts, changing the shell won't work
      if grep -Eq "^${username_of_current_user}" /etc/password; then
        should_change_shell="true"
      fi
    fi
    if [[ "$should_change_shell" == "true" ]]; then
      sudo chsh -s "$shell_path" "$username_of_current_user"
    fi
  fi
}

function gem_install_or_update() {
  if gem list "$1" --installed > /dev/null; then
    gem update "$@"
  else
    gem install "$@"
  fi
}

# we need vim 8.2 and ppa:jonathonf/vim seems fail
# installation on ubuntu 20.04 so compile from source instead
# ubuntu 20.04 has 8.1 by default in apt
function install_vim_from_source() {
  if ! command -v vim >/dev/null || vim --cmd 'if v:version < 802 | q | else | cq | fi' ; then
    # sudo apt install ncurses-dev
    curl  --fail -sL "https://github.com/vim/vim/archive/refs/tags/v${vim_version}.zip" -o /tmp/vim.zip
    unzip /tmp/vim.zip -d /tmp/vim
    pushd "/tmp/vim/vim-${vim_version}/src"
    ./configure
    make
    sudo make install
    popd
  fi
}

function get_additional_apt_keys() {
  # kubectl
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

  # ubuntu 18.04 for openssl1.0
  # echo "deb http://security.ubuntu.com/ubuntu bionic-security main" | sudo tee /etc/apt/sources.list.d/bionic-security.list

  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo apt-key fingerprint 0EBFCD88
  sudo add-apt-repository -y \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
  sudo add-apt-repository -y \
    "deb http://security.ubuntu.com/ubuntu \
    $(lsb_release -cs)-security \
    main"

  if ! ubuntu_greater_than_18_04 ; then
    # thoughtbot rcm
    sudo add-apt-repository -y ppa:martin-frost/thoughtbot-rcm
    # sudo add-apt-repository -y ppa:jonathonf/vim
  fi
}

function add_or_update_asdf_plugin() {
  local name="$1"
  local url="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$url"
  else
    asdf plugin-update "$name"
  fi
}

function install_asdf_language() {
  local language="$1"
  local version

  # FIXME: 17.7.0 seems to be broken with the newest nodejs plugin. It sometimes lists the version
  # with: "asdf list-all nodejs" but gives the error "node-build: definition not found: 17.7.0"
  # when trying to install it so avoid it for now
  version="$(asdf list-all "$language" | grep -v "[a-z]" | grep -vE "17\.7" | tail -1)"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

function add_user_to_docker_group() {
  local username_of_current_user
  username_of_current_user="$(whoami)"
  if grep -Eq docker /etc/group; then
    groups_for_user=$(id -nG "$username_of_current_user")
    if ! grep -qw "docker" <<< "$groups_for_user"; then
      sudo usermod -a -G docker "$username_of_current_user"
    fi
  fi
}

function set_number_of_cores_for_bundler() {
  if is_mac ; then
    number_of_cores=$(sysctl -n hw.ncpu)
  elif [[ -f /proc/cpuinfo ]]; then
    number_of_cores=$(grep -c processor /proc/cpuinfo)
  fi

  if [[ -n "$number_of_cores" ]]; then
    bundle config --global jobs $((number_of_cores - 1))
  fi
}

function install_stern() {
  local version="1.21.0"
  if command -v stern >/dev/null; then
    stern_version_output="$(stern --version)"
    if grep -q "$version" <<< "$stern_version_output"; then
      return # got it already
    fi
  fi
  local tmp_output="/tmp/stern_$(date +%s)"
  mkdir -p "$tmp_output"
  pushd "$tmp_output"

  curl -L --fail "https://github.com/stern/stern/releases/download/v${version}/stern_${version}_linux_amd64.tar.gz" -o "$tmp_output/stern_${version}_linux_amd64.tar.gz"
  tar xpvf *.tar.gz
  sudo cp stern /usr/local/bin/stern
  popd
  rm -rf "$tmp_output"
}

function install_kubectl() {
  local desired_kubectl_version=''
  if [[ -n "$NO_TERM_LIMITS_KUBECTL_VERSION" ]]; then
    desired_kubectl_version="v${NO_TERM_LIMITS_KUBECTL_VERSION}"
  else
    desired_kubectl_version=$(curl -L -s https://dl.k8s.io/release/stable.txt)
  fi
  local current_version=''
  if command -v kubectl >/dev/null; then
    current_version=$(kubectl version --client | perl -p -e 's/.*GitVersion:"(v[^"]+)".*/\1/')
  fi
  if [[ "$current_version" != "$desired_kubectl_version" ]]; then
    local architecture
    architecture=$(uname -m)
    if [[ "$architecture" == 'x86_64' ]]; then
      architecture=amd64
    fi
    local os_type='linux'
    if is_mac ; then
      os_type='darwin'
    fi
    curl -L "https://dl.k8s.io/release/${desired_kubectl_version}/bin/${os_type}/${architecture}/kubectl" -o /tmp/kubectl
    chmod +x /tmp/kubectl
    sudo mv /tmp/kubectl /usr/local/bin
    sudo chown root: /usr/local/bin/kubectl
  fi
}

# shellcheck disable=SC1090
if is_mac ; then
  if [ -d "$HOMEBREW_PREFIX" ]; then
    if ! [ -r "$HOMEBREW_PREFIX" ]; then
      sudo chown -R "$LOGNAME:admin" /usr/local
    fi
  else
    sudo mkdir "$HOMEBREW_PREFIX"
    sudo chflags norestricted "$HOMEBREW_PREFIX"
    sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
  fi

  if ! command -v brew >/dev/null; then
    echo "Installing Homebrew ..."
    NONINTERACTIVE=1 /bin/bash -c \
      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  # regardless of whether or not we just installed brew, add brew stuff to the PATH
  # in case we do not yet do so via dotfiles since it's too early in the setup process.
  if [[ -f /usr/local/bin/brew ]]; then
    export PATH="/usr/local/bin:$PATH"
  else
    export PATH="/opt/homebrew/bin:$PATH"
  fi

  if brew list | grep -Fq brew-cask; then
    echo "Uninstalling old Homebrew-Cask ..."
    brew uninstall --force brew-cask
  fi

  echo "BREW LIST"
  brew list

  #
  # if brew list | grep -Fq git; then
  #   echo "Uninstalling old Homebrew-Cask ..."
  #   brew uninstall --force brew-cask
  # fi

  # git_version_qualifier=''
  # echo "GITHUB_ACTIONS debug: $GITHUB_ACTIONS"
  # if [[ "${GITHUB_ACTIONS:-}" == "true" ]]; then
  #   # apparently they install this specific version of git via homebrew, so we would need to force link to change it. just comply in CI.
  #   git_version_qualifier="@2.35.1"
  # fi

  echo "Updating Homebrew formulae ..."
  # https://github.com/Homebrew/brew/issues/1151
  brew update --force

  brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"

# Unix
brew "universal-ctags", args: ["HEAD"]
brew "git${git_version_qualifier}"
brew "openssl"

# rcm for rcup, etc.
brew "rcm"

brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watchman"
brew "zsh"

# GitHub
brew "gh"

# Image manipulation
brew "imagemagick@6"

# Programming language prerequisites and package managers
brew "libyaml" # should come after openssl
brew "coreutils"
brew "yarn"
cask "gpg-suite"

# Databases
brew "redis", restart_service: :changed

# jq is just awesome
brew "jq"

# gnu-sed so we can use sed in scripts the way it was intended (via hot_sed)
brew "gnu-sed"

# libxml for libxml-ruby
brew "libxml2"

# libxslt for hydra-services
brew "libxslt"

# wget because it's nice to have around for scripting
brew "wget"

# htop to monitor local processes
brew "htop"

# stern to make tailing kubernetes logs more awesome
brew "stern"

# telnet because we use computers
brew "telnet"

# colordiff for test_command_on_git_repo, etc
brew "colordiff"

# bash because otherwise you are running bash 3
brew "bash"

# (gnu) parallel
brew "parallel"

# cat commands with syntax highlighting
brew "bat"

brew "gnu-getopt"

# super-fast grep in rust
brew "ripgrep"

# for ruby install
brew "shared-mime-info"

# for linting shell scripts
brew "shellcheck"

# useful utility
brew "watch"
EOF

  install_kubectl

  if grep -q "asdf" /tmp/brew_list; then
    echo 'asdf should be installed in ~/.asdf by the thoughtbot laptop setup script, so uninstalling from homebrew'
    brew uninstall asdf
  fi
else
  sudo apt-get update
  # automake so we can sh autogen.sh to install tmux below
  sudo apt-get install -y \
    at \
    automake \
    build-essential \
    colordiff \
    curl \
    espeak \
    expect \
    gettext-base \
    htop \
    imagemagick \
    jq \
    language-pack-en \
    libbz2-dev \
    libcurl4-openssl-dev \
    libfcgi \
    libfcgi-dev \
    libffi-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2-dev \
    libxslt1-dev \
    libyaml-dev \
    net-tools \
    openssl \
    openssh-server \
    parallel \
    rsync \
    screen \
    shellcheck \
    silversearcher-ag \
    software-properties-common \
    sqlite3 \
    unzip \
    vim-gtk \
    wget \
    zlib1g-dev \
    zsh

  if ubuntu_greater_than_18_04 ; then
    if [[ "$NO_TERM_LIMITS_INSTALL_VIM_FROM_SOURCE" != "false" ]]; then
      install_vim_from_source
    fi
    additional_packages="$additional_packages tmux"
  else
    # so we can install tmux 3 on ubuntu 18.04
    if [[ "$NO_TERM_LIMITS_INSTALL_TMUX_FROM_SOURCE" != "false" ]]; then
      if ! command -v tmux >/dev/null || ! grep -Eq 'tmux 3' <<< "$(tmux -V)"; then
        sudo apt update && sudo apt install -y libevent-dev libncurses5-dev byacc bison
        rm -fr /tmp/tmux
        git clone https://github.com/tmux/tmux.git /tmp/tmux
        pushd /tmp/tmux
        git checkout 3.0
        sh autogen.sh
        ./configure && make
        sudo make install
        popd
        rm -fr /tmp/tmux
      fi
    fi
    # rely on vim-gtk on ubuntu 18.04
    # additional_packages="$additional_packages vim"
  fi

  get_additional_apt_keys

  if ubuntu_greater_than_18_04 ; then
    additional_packages="$additional_packages ripgrep universal-ctags"
  fi

  sudo apt-get update
  sudo apt-get install -y --allow-change-held-packages \
    containerd.io \
    docker-ce \
    docker-ce-cli \
    rcm $additional_packages

  add_user_to_docker_group

  install_stern
  install_kubectl
fi

case "$SHELL" in
  */zsh)
    if [ "$(command -v zsh)" != '/usr/local/bin/zsh' ] ; then
      update_shell
    fi
    ;;
  *)
    update_shell
    ;;
esac

echo "Configuring asdf version manager ..."
if [ ! -d "$HOME/.asdf" ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch "$asdf_branch_name"
fi

if [[ "$NO_TERM_LIMITS_INSTALL_ASDF_LANGUAGES" != "false" ]]; then
  source "$HOME/.asdf/asdf.sh"
  add_or_update_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
  add_or_update_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"

  echo "Installing latest Ruby ..."
  install_asdf_language "ruby"
  gem update --system
  set_number_of_cores_for_bundler

  echo "Installing latest Node ..."
  install_asdf_language "nodejs"
fi
